version: '3'

services:
  grpcserver:
    container_name: grpcserver
    build:
      context: ./
      dockerfile: ./docker/grpc/Dockerfile
    environment:
      VK_TOKEN: "a72e938fa72e938fa72e938f5da757bb61aa72ea72e938fc600c8aeb9403ffae922608a"
      GRPC_PORT: "8090"
    ports:
      - "8090:8090"

  httpserver:
    container_name: httpserver
    build:
      context: ./
      dockerfile: ./docker/http/Dockerfile
    environment:
      HTTP_PORT: "8080"
      GRPC_PORT: "8090"
    depends_on:
      - grpcserver
    ports:
      - "8080:8080"
