// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package mutual

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// MutualClient is the client API for Mutual service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MutualClient interface {
	GetMutual(ctx context.Context, in *GetMutualRequest, opts ...grpc.CallOption) (*GetMutualResponse, error)
}

type mutualClient struct {
	cc grpc.ClientConnInterface
}

func NewMutualClient(cc grpc.ClientConnInterface) MutualClient {
	return &mutualClient{cc}
}

func (c *mutualClient) GetMutual(ctx context.Context, in *GetMutualRequest, opts ...grpc.CallOption) (*GetMutualResponse, error) {
	out := new(GetMutualResponse)
	err := c.cc.Invoke(ctx, "/mutual.mutual/GetMutual", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MutualServer is the server API for Mutual service.
// All implementations must embed UnimplementedMutualServer
// for forward compatibility
type MutualServer interface {
	GetMutual(context.Context, *GetMutualRequest) (*GetMutualResponse, error)
	mustEmbedUnimplementedMutualServer()
}

// UnimplementedMutualServer must be embedded to have forward compatible implementations.
type UnimplementedMutualServer struct {
}

func (UnimplementedMutualServer) GetMutual(context.Context, *GetMutualRequest) (*GetMutualResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMutual not implemented")
}
func (UnimplementedMutualServer) mustEmbedUnimplementedMutualServer() {}

// UnsafeMutualServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MutualServer will
// result in compilation errors.
type UnsafeMutualServer interface {
	mustEmbedUnimplementedMutualServer()
}

func RegisterMutualServer(s grpc.ServiceRegistrar, srv MutualServer) {
	s.RegisterService(&Mutual_ServiceDesc, srv)
}

func _Mutual_GetMutual_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMutualRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MutualServer).GetMutual(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mutual.mutual/GetMutual",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MutualServer).GetMutual(ctx, req.(*GetMutualRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Mutual_ServiceDesc is the grpc.ServiceDesc for Mutual service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Mutual_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "mutual.mutual",
	HandlerType: (*MutualServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetMutual",
			Handler:    _Mutual_GetMutual_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "mutual.proto",
}
